### ISSUE TITLE
dc.spool(path)[0] try to read deleted file

### ISSUE THREAD

**Issue by RosieZhu** [DASDAE/dascore#106]
When using `dc.spool(path)[0]`, it returns 
`FileNotFoundError: [Errno 2] No such file or directory: '/Users/rosie/Documents/aceffl/DAS/01_Raw/DAS_P10/SM_BriscoeC3339H_CF_P10_UTC_20211224_000909.913.tdms'`

which is a file I deleted... the full error message is below:

`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Input In [10], in <cell line: 5>()
      1 # path = fileloc
      2 
      3 # pa = dc.read(path)[0]
      4 # or
----> 5 pa = dc.spool(fileloc)[0]
      6 pa

File /opt/anaconda3/lib/python3.9/site-packages/dascore/core/spool.py:123, in DataFrameSpool.__getitem__(self, item)
    122 def __getitem__(self, item):
--> 123     out = self._get_patches_from_index(item)
    124     # a single index was used, should return a single patch
    125     if not isinstance(item, slice):

File /opt/anaconda3/lib/python3.9/site-packages/dascore/core/spool.py:158, in DataFrameSpool._get_patches_from_index(self, df_ind)
    156     raise IndexError(msg)
    157 joined = df1.join(source.drop(columns=df1.columns, errors="ignore"))
--> 158 return self._patch_from_instruction_df(joined)

File /opt/anaconda3/lib/python3.9/site-packages/dascore/core/spool.py:168, in DataFrameSpool._patch_from_instruction_df(self, joined)
    165 for patch_kwargs in df_dict_list:
    166     # convert kwargs to format understood by parser/patch.select
    167     kwargs = _convert_min_max_in_kwargs(patch_kwargs, joined)
--> 168     patch = self._load_patch(kwargs)
    169     select_kwargs = {
    170         i: v for i, v in kwargs.items() if i in patch.dims or i in patch.coords
    171     }
    172     out_list.append(patch.select(**select_kwargs))

File /opt/anaconda3/lib/python3.9/site-packages/dascore/clients/dirspool.py:124, in DirectorySpool._load_patch(self, kwargs)
    122 def _load_patch(self, kwargs) -> Self:
    123     """Given a row from the managed dataframe, return a patch."""
--> 124     patch = dc.read(**kwargs)[0]
    125     return patch

File /opt/anaconda3/lib/python3.9/site-packages/dascore/io/core.py:342, in read(path, file_format, file_version, time, distance, **kwargs)
    336     file_format, file_version = get_format(
    337         path,
    338         file_format=file_format,
    339         file_version=file_version,
    340     )
    341 formatter = FiberIO.manager.get_fiberio(file_format, file_version)
--> 342 return formatter.read(
    343     path, file_version=file_version, time=time, distance=distance, **kwargs
    344 )

File /opt/anaconda3/lib/python3.9/site-packages/dascore/io/tdms/core.py:79, in TDMSFormatterV4713.read(self, path, time, distance, **kwargs)
     67 def read(
     68     self,
     69     path: Union[str, Path],
   (...)
     72     **kwargs
     73 ) -> dc.BaseSpool:
     74     """
     75     Read a silixa tdms file, return a DataArray.
     76 
     77     """
---> 79     with open(path, "rb") as tdms_file:
     80         # get time array. If an input isn't provided for time we return everything
     81         if time is None:
     82             time = (None, None)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/rosie/Documents/aceffl/DAS/01_Raw/DAS_P10/SM_BriscoeC3339H_CF_P10_UTC_20211224_000909.913.tdms'`

**Comment by d-chambers** [comment]
Ah, interesting. I hadn't thought of the case where files are removed from the directory. 

Probably the easiest fix is to delete the index file, then re-update. The index file should be named ".dascore_index.h5". 

I will think of a cleaner way to handle this case.

**Comment by RosieZhu** [comment]
Yep, I renamed the folder and it re-indexed!

Thank you!
Rosie
