### ISSUE TITLE
Need to improve docs on adding examples in docstrings

### ISSUE THREAD

**Issue by d-chambers** [DASDAE/dascore#110]
**Description**
It isn't as clear as it should be how to add docstring examples.

**Comment by d-chambers** [comment]
Want to tackle this one @aissah?

**Comment by aissah** [comment]
Sure! As always, I will most likely be coming to you for some directions

**Comment by d-chambers** [comment]
I am going to close this, as the original impetus was a limited understanding of docstrings. Feel free to re-open if you want  to add anything to to docs.
