### ISSUE TITLE
Documentation typehints

### ISSUE THREAD

**Issue by d-chambers** [DASDAE/dascore#138]
## Description
We need to fix a few things in the [Patch documentation](https://dascore.org/api/dascore/core/patch/Patch.html)
- type hints which use numpy's ArrayLike are inscrutable 
- The parameter table should support indentation.

**Comment by ahmadtourei** [comment]
@d-chambers Could you please elaborate more on these? I may resolve this later this week.

**Comment by d-chambers** [comment]
Hey @ahmadtourei, I just forgot to close this as part of #201. There are several other things I have been meaning to do you can work on though, I will open/elaborate on other issues a bit later today.
