### ISSUE TITLE
Sub Directory Missed on Spool

### ISSUE THREAD

**Issue by CDCsbai** [DASDAE/dascore#149]
## Description

Spool index's subdirectory's without maintaining links, causing missing files error on trying to access that data. 

## Example
<img width="878" alt="bugSpool" src="https://github.com/DASDAE/dascore/assets/73720395/1f5e5d3b-2fb0-4682-9236-9ae36150ec13">

## Versions
 - OS [Windows 10]
 - DasCore Version [ 0.0.10]:
 - Python Version [3.10]:

**Comment by d-chambers** [comment]
closed by #150, re-open if you can reproduce.
