### ISSUE TITLE
Colorbar position for figures with subplots

### ISSUE THREAD

**Issue by jinwar** [DASDAE/dascore#174]
It seems that the colorbar position is not handled appropriately. 
Probably good to allow user to turn off colorbar in the waterfall plot. 

![image](https://github.com/DASDAE/dascore/assets/2571950/ba1c70c4-c7c7-4fd5-8372-2753677df5c3)

**Comment by jinwar** [comment]
dascore version: 0.0.11

**Comment by d-chambers** [comment]
Ok, I made a few tweaks, will open a PR soon. It now looks like this when you pass `cmap=None`

![image](https://github.com/DASDAE/dascore/assets/11671536/9fa0a275-9325-422e-8679-61f39d4fe242)

For subplots, you will still have to mess with the axis labels and such to make it look nice, but that should be doable with the returned axes.

**Comment by d-chambers** [comment]
Closed by #175
