### ISSUE TITLE
Can't get gauge length from attributes - PRODML v. 2.0 format

### ISSUE THREAD

**Issue by ahmadtourei** [DASDAE/dascore#194]
## Description
I can see "GaugeLength" in the attributes list using HDFView software. However, I can't get the value using: ```patch_0.attrs['gauge_length']```
Please note that I can get some other attributes such as sampling interval or channel spacing.

Data format: ONYX - PRODML v. 2.0

## Example
```python
import dascore as dc
sp = dc.spool(data_path)
patch_0 = sp[0]
gauge_length = patch_0.attrs['gauge_length']
```

### Error:
```python
AttributeError                            Traceback (most recent call last)
Cell In[3], line 12
      8 print(patch_0.attrs)
     11 # get sampling rate, channel spacing, and gauge length
---> 12 gauge_length = patch_0.attrs['gauge_length']
     13 print("Gauge length = ", gauge_length)
     14 channel_spacing = patch_0.attrs['d_distance']

File [~/anaconda3/envs/py10/lib/python3.10/site-packages/dascore/core/schema.py:94](https://vscode-remote+wsl-002bubuntu.vscode-resource.vscode-cdn.net/home/ahmadtourei/coding/fervo/iDAS_stimulation_stage8/LF_DAS/~/anaconda3/envs/py10/lib/python3.10/site-packages/dascore/core/schema.py:94), in PatchAttrs.__getitem__(self, item)
     93 def __getitem__(self, item):
---> 94     return getattr(self, item)

AttributeError: 'PatchAttrs' object has no attribute 'gauge_length'
```

## Versions
 - OS [e.g. Ubuntu 20.04]: Ubuntu 20.04
 - DasCore Version [e.g. 0.0.5]: 0.0.12
 - Python Version [e.g. 3.10]: 3.10

**Comment by d-chambers** [comment]
Looks like we  just need to add gauge length to the prodml attributes [here](def _get_prodml_attrs(fi, extras=None, cls=PatchAttrs). I am refactoring some of the IO stuff so I will add that in the [io_refactor branch](https://github.com/DASDAE/dascore/tree/io_refactor). We might consider making gauge_length a default patch attribute?

**Comment by ahmadtourei** [comment]
Thanks for your comment! Where do we define default patch attributes?

**Comment by d-chambers** [comment]
> Where do we define default patch attributes?

Its in dascore/core/schema
