### ISSUE TITLE
Time axis label in waterfall plots

### ISSUE THREAD

**Issue by d-chambers** [DASDAE/dascore#213]
## Description
The time axis label in the waterfall plot should just read "time" not "time(s)". This should also work for other dimensions not named "time" but are datetime64 types.

**Comment by ahmadtourei** [comment]
The time axis label is "Time" currently. Please see below:
![image](https://github.com/DASDAE/dascore/assets/92008628/05cd0b3e-d484-445f-9de1-aa51db4a55cb)

Data format: ONYX - PRODML v. 2.0

**Comment by d-chambers** [comment]
Which version of DASCore are you on?

**Comment by ahmadtourei** [comment]
DASCore version: 0.0.12

**Comment by d-chambers** [comment]
Ah ok. I think this is only an issue in master (unreleased).
