### ISSUE TITLE
Recipes side menu missing

### ISSUE THREAD

**Issue by d-chambers** [DASDAE/dascore#254]
## Description

It appears that #253 broke something with the recipes. The [recipe page in the dev docs](https://dascore.quarto.pub/dascore/recipes/overview.html) no longer has a left menu. 

Compare this: 

![image](https://github.com/DASDAE/dascore/assets/11671536/dad9477a-04cb-4f75-9979-93b75d20ec30)

With this:
![image](https://github.com/DASDAE/dascore/assets/11671536/0c1c956e-105c-4080-8f78-19c47be2294e)

**Comment by ahmadtourei** [comment]
Thanks for catching this!
