### ISSUE TITLE
Python 3.12 conda installation error 

### ISSUE THREAD

**Issue by seis-hyejeong** [DASDAE/dascore#325]
I tried installing dascore with conda (Python 3.12) and received the following error

ImportError: cannot import name 'PydanticUndefined' from 'pydantic_core' (unknown location)

**Comment by d-chambers** [comment]
Hey @seis-hyejeong,

Thanks for filling the issue. See the [corresponding issue](https://github.com/pydantic/pydantic/issues/8429) for pydantic. 

In short, the workaround is to uninstall and re-install pydantic_core with pip:

```bash
pip uninstall pydantic_core
pip install pydantic_core
```

I will keep this open until the downstream issues is resolved so others can easily find the workaround.

**Comment by samuelcolvin** [comment]
This should now be solved in condaforge.

**Comment by d-chambers** [comment]
> This should now be solved in condaforge.

Thanks so much @samuelcolvin and happy holidays 🎄
