### ISSUE TITLE
Conda installation issues

### ISSUE THREAD

**Issue by d-chambers** [DASDAE/dascore#357]
## Description
As part of the DASCore manuscript, some authors mentioned they had issues installing DASCore with conda. We need to look into this more and see if there is anything we can do to speed this up, apart from recommending Mamba. 

Unfortunately, I don't know anything about the OS/installation they were using but we should test the current version on the major ones.

Anyone who has a few minutes, if you could install a new DASCore conda env on your machine and report back in this issue on how long it takes and if you encounter any problems that would be helpful. Also, please list your OS, python version, and conda version. 

_edit:_
You can just copy and paste this on a posix system:

```bash
time conda create -n dascore_new -y -c conda-forge dascore
```

**Comment by danesnick** [comment]
Hey Derrick,

I did a couple test installations on machines I had access to. 

- Ubuntu 22.04.3 LTS via Windows Subsystem for Linux (Kernel version 5.15.146.1-microsoft-standard-WSL2) using Anaconda 2024.02: installed without any issue and quite quickly actually. See command below:
```
(base) ndanes@12600K-DESKTOP:~$ time conda create -n dascore_stable -c conda-forge dascore -y
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/ndanes/anaconda3/envs/dascore_stable

  added / updated specs:
    - dascore
...OMITTED...
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate dascore_stable
#
# To deactivate an active environment, use
#
#     $ conda deactivate


real    0m40.574s
user    0m32.389s
sys     0m1.844s
(dascore_stable) ndanes@12600K-DESKTOP:~$ python --version
Python 3.12.2
```
Also setting
- macOS Sonoma 14.3.1 (Apple M1 2020 Macbook Pro 16GB): Installed without issue using Anaconda 2024.02 arm64. I will say it took noticeably longer to install here, but didn't time it. Also Python 3.12.2

- Wendian (CentOS 7) Scratch file system using Anaconda 2023.07: 
```
real 6m0.050s
user 1m57.693s
sys 0m26.592s
```
Installed without issue, also Python 3.12.2.

**Comment by d-chambers** [comment]
Thanks @danesnick, so no issues on any of the installations but the Sonoma 14 installation was much slower than 6m right?

**Comment by ahmadtourei** [comment]
I just tested this on my Windows machine and could successfully install DASCore on a new environment using conda in ~119 seconds.

OS: Windows 10 (version 10.0.19045)
Python: 3.12.2
Conda: 23.1.0
DASCore: 0.1.0

**Comment by sboltz** [comment]
I just tested it with Ubuntu 22 and it took ~90 seconds.

real	1m37.128s
user	1m2.841s
sys	0m19.311s

Regarding the "just use mamba" suggestion, libmamba is actually now the default package solver for new versions of conda as of about mid-2023: https://conda.org/blog/2023-07-05-conda-libmamba-solver-rollout/. Based on the style of the output from my install just now, I'm fairly certain that's what it used (I haven't used the python install on my personal machine in quite some time, though, so I'm not certain).

**Comment by danesnick** [comment]
> Thanks @danesnick, so no issues on any of the installations but the Sonoma 14 installation was much slower than 6m right?

I didn't notice any issues, but yes it was a bit slower.

**Comment by SeunghooKim** [comment]
I did a couple of tests as well:
1) macOS Sonoma 14.3.1 (Apple M1 2021 Macbook Pro 16GB): worked without a problem, didn't give me time but it didn't seem to take too long.

2) GC compute engine (8 vCPU, 4 core, 30 GB memory): 
real    2m22.070s                                                                
user    1m56.196s                                                                
sys     0m13.264s 

3) Windows 11 laptop: 
real    0m53.067s
user    0m36.376s
sys     0m7.788s

**Comment by SeisMatt** [comment]
Similarly to Seunghoo, I tested this on an Apple M1 Macbook Pro 32 GB, but on a slightly older OS – 12.6.6
No issue, and no time, but was setup in about under a minute.

**Comment by d-chambers** [comment]
Ok, thanks everyone. I think we have sufficient data to say this is not a wide-spread issue. I will close for now.
