### ISSUE TITLE
patch.dft() does not change data_type 

### ISSUE THREAD

**Issue by ahmadtourei** [DASDAE/dascore#390]
## Description

`patch.dft()` does not change data_type attribute so when make waterfall plot from a patch with strain_rate data type (e.g., `patch.dft("time").abs().viz.waterfall()`), the colorbar has `strain_rate ` label.

## Versions
 - OS [e.g. Ubuntu 20.04]:
 - DasCore Version [e.g. 0.0.5]:
 - Python Version [e.g. 3.10]:

**Comment by d-chambers** [comment]
hmmm.... should `Patch.dft` just remove the data_type tag? Or maybe it is still technically correct since it is derived from strain rate, its just not in strain rate units?

**Comment by ahmadtourei** [comment]
Yeah, I'm not sure either. Keeping data_type as strain rate can be a bit misleading. Also, do we need it for `patch.idft()`? If not, removing data_type sounds okay to me. Or, maybe updating data_type to `amplitude` if `real=True` and `complex_number` if `real=False`? Then, we may make the `patch.abs()` update patch's data_type to `amplitude` if the original `data_type` is `complex`. What do you think?
