### ISSUE TITLE
velocity_to_strain_rate function issues

### ISSUE THREAD

**Issue by ahmadtourei** [DASDAE/dascore#396]
## Description

`velocity_to_strain_rate` patch function should divide the result by the `gauge_length`. Also, we should support `gauge_length > distance_step`. 
## Versions
 - OS [e.g. Ubuntu 20.04]:
 - DasCore Version [e.g. 0.0.5]:
 - Python Version [e.g. 3.10]:

**Comment by d-chambers** [comment]
closed by #399
