### ISSUE TITLE
spool.concatenate with new dimension has incorrect shape

### ISSUE THREAD

**Issue by d-chambers** [DASDAE/dascore#404]
## Description
Specifying a new dimension in `BaseSpool.concatenate` returns a spool whose patch has only a length of 1 in the new dimension, regardless of the input shape.

## Example
```python
import dascore as dc

sp = dc.get_example_spool()
new = sp.concatenate(new_dim=1)
patch = new[0] 

assert patch.shape[-1] == len(sp)  # fails
```

## Expected behavior
The new dimension should be the same as the length of the spool. 

## Versions
 - OS [e.g. Ubuntu 20.04]:
 - DasCore Version [e.g. 0.0.5]:
 - Python Version [e.g. 3.10]:

**Comment by d-chambers** [comment]
Turns out this isn't a bug. In the example above the time dimensions don't match so the patches cannot be concatenated along a new dimension. I will create a PR that clarifies this in the docstrings.

**Comment by ahmadtourei** [comment]
Yes that is correct. 
I have patches with `dft` history so they still have the `time` coordinate but two dimensions (`distance` and `ft_time`) which are identical. What would be the best strategy to concatenate them? I can update their coords and drop the `time` coord so I can concatenate but that way I can't do `idft` on them.

**Comment by ahmadtourei** [comment]
can we add an `ignore_coord` argument support so we can concatenate these patches?

**Comment by d-chambers** [comment]
So the flag would indicate if non-dimensional coords should be dropped right? Or do you have to name the coords to ignore?

**Comment by ahmadtourei** [comment]
Either way would work. We can have an `ignore_coord="time"` to ignore (and not to drop) the `time` coord when concatenating the patches. Or, having something like `conflict="ignore_diff_coords"` to ignore all unidentical coords (such as the `time` coord in my `dft` patches).

**Comment by ahmadtourei** [comment]
I thought a bit more about it and agree with you about how ignoring the coordinates can be challenging. I'd suggest we include an example of dropping the coord before concatenating to clarify this in the spool's tutorial. I have also implemented a new test for this that I'll push in a bit.
