### ISSUE TITLE
spool works in pip install but not in developer install

### ISSUE THREAD

**Issue by jinwar** [DASDAE/dascore#51]
![image](https://user-images.githubusercontent.com/2571950/190838109-ed9b50a8-f0e9-484c-9e85-8a5a495362ca.png)

This code worked well with pip install.

**Comment by jinwar** [comment]
It seems that some link is broken... even the simplest function cannot be found. 

![image](https://user-images.githubusercontent.com/2571950/190838310-1605b67e-4d45-4225-9fe1-25c0053b3d72.png)

**Comment by d-chambers** [comment]
This looks weird. Can you try it in the terminal outside of jupyter to see if there is some wires crossed with your python environments?  Also, you don't have a python file named dascore in the same directory right?

**Comment by jinwar** [comment]
It works with python terminal interaction, but not with ipython. Could this be related to I have previously install and uninstalled dascore through pip? I actually create a conda environment from the yml file for this but it still does not work for ipython.

**Comment by d-chambers** [comment]
The only reason I can think of is that the ipython and python binaries are from different environments. 

For example, on linux:

```bash
conda activate dascore 

which python  # ../anaconda3/envs/dascore/bin/python
which ipython  # ../anaconda3/envs/dascore/bin/ipython
```
If the python and ipython binaries are in the same directory you have me stumped. If not, that is the issue.

**Comment by d-chambers** [comment]
I am going to close this for now since I think we resolved the issue with a reinstall. Please re-open if it crops up again.
