### ISSUE TITLE
Error is creating Time Series from DAS data

### ISSUE THREAD

**Issue by SharifahAli** [DASDAE/dascore#67]
**Description**
The goal is to create time series from the recorded data during multiphase testing. The code is set to run and read each second of the DAS data and calculate some parameters. At some point in the calculation, it stops and doesn't complete going through the whole data.

**To Reproduce**

```python
bgtime = np.datetime64('2022-05-12 16:04:45')
dt = np.timedelta64(1,'s')

freq_bands = [[1,10],[10,100],[100,500],[500,1000],[1000,5000]]
FBEs = [[] for i in freq_bands] #to create a list of a list
timestamps = []
current_time = bgtime
for i in range(14400):
    gjsignal.print_progress(i)
    try:
        data1 = spool.select(time=(current_time,current_time+dt))
        dataa = dascore.utils.patch.merge_patches(data1)[0]
        DASdata1 = Data2D_XT.Patch_to_Data2D(dataa)
        DASdata1.apply_gauge_length(3)  # apply a gauge length 3x channel spacing
        DASdata1.select_depth(50,100)
        f,amp = spectrum_analysis(DASdata1)
        for ifreq in range(len(freq_bands)):
            FBEs[ifreq].append(get_FBE(f,amp,freq_bands[ifreq][0],freq_bands[ifreq][1]))
        timestamps.append(current_time)
    except:
        print('there is an error')
    current_time += dt
```

**Expected behavior**
It is expected to go through the whole data set and create the time series over the four hours of recorded data. 

**Versions (please complete the following information):**
 - OS: [Windows 10 Pro 19045.2130]
 - DasCore Version [Not sure]
 - Python Version [3.9]

**Comment by d-chambers** [comment]
Hi @SharifahAli, thanks for filing the issue! I edited your text so [github code highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) would display the code nicely. 

It looks like you have a try/except catching the error that is being raised. The first step is probably to remove that and run it again so we can see the traceback (the exact error python spits out). The traceback will help us diagnose what is going on.  It would be helpful to edit your comment to include the traceback in there too.

**Comment by d-chambers** [comment]
Hey @SharifahAli,

I think this is fixed now. I will push out a new version.  Please install the new version and try it out. If the problem persists please re-open this issue and let me know.
