### ISSUE TITLE
spool get_content output should be sorted by time

### ISSUE THREAD

**Issue by jinwar** [DASDAE/dascore#81]
Currently the get_content() output is random in time:
![image](https://user-images.githubusercontent.com/2571950/204572440-038b8063-74ba-4d09-81c1-cf3612af2e69.png)

**Expected behavior**
spool get_content output should be sorted by time

**Comment by d-chambers** [comment]
The index of the spool is appended to as new files are added (when `.update()` is called), so the new files just appear at the end. This makes it hard to sort the contents in the index itself, but `get_contents` returns a dataframe, you can just call `sort_values`

```python
import dascore as dc

spool = dc.get_example_spool()
contents_sorted = spool.get_contents().sort_values('time_min')
```

Would that work?

**Comment by d-chambers** [comment]
Closing for now, @jinwar feel free to re-open if you want to discuss more.
